<a href="https://colab.research.google.com/github/sara-javed/Pytorch-week4/blob/main/Pytorch_week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**00. PyTorch** **Fundamentals**

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/


Discussions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


**Introduction to** **Tensors**




*   Tensors are the fundamental building block of machine learning.


*   Their job is to represent data in a numerical way.















**Scalar**

In [ ]:
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

**Vector**

In [ ]:
#vector
import torch
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector[0]

tensor(7)

**Matrix**

In [ ]:
#matrix
MATRIX = torch.tensor([[2,4],[5,7]])
print(MATRIX)

tensor([[2, 4],
        [5, 7]])


In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

**Tensor**

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,3,5],[7,9.0,9],[3,5,7]]])
print(TENSOR)

tensor([[[1., 3., 5.],
         [7., 9., 9.],
         [3., 5., 7.]]])


In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1., 3., 5.],
        [7., 9., 9.],
        [3., 5., 7.]])

**Random** **tensors**

why Random tensors?

Random tensors are important because the way many neural network learn is that they start with tensor full of random numbers and than adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at the data -> update the random numbers

In [ ]:
#creating a random tensor of size(3,4)
random_tensor = torch.rand(size=(3,4))
print(random_tensor)

tensor([[0.5786, 0.9601, 0.9123, 0.5552],
        [0.4645, 0.1637, 0.8830, 0.2632],
        [0.5913, 0.8201, 0.2625, 0.9767]])


In [ ]:
random_tensor.ndim

2

**Real World Example of Tensor**

In [ ]:
# Shape = [height,width,color_channals]
# Example = [224,224,3]

In [ ]:

# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor.dtype
#by default all the tensors datatype is float unless explicitly changed.

torch.float32

**Zero and One tensors**

In [ ]:
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zeroes_tensors = torch.zeros(2,2,3)
zeroes_tensors.dtype , zeroes.ndim

(torch.float32, 2)

In [ ]:
ones_tensors = torch.ones(2,5)
ones_tensors


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

**Creating a range of Tensors and Tensors-likes**





**arange()**

In [ ]:
import torch
one_to_ten = torch.arange(1,10)
one_to_ten


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten.ndim

1

In [ ]:
random_range=torch.arange(start=10,end=1000,step=100)
random_range

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [ ]:
#creating tensor like
one_to_ten.shape

torch.Size([9])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros.shape

torch.Size([9])

In [ ]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

**Tensor** **datatypes**

**Note:** Tensor datatype is one of the 3 big errors you'll run in the pytorch & deeplearning


1.   Tensor not right datatype
2.   Tensor not right shape
3.   Tensor not on the right device
   





In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,#what datatype our tensor do have
                               device=None,#what device our tensor will run on
                               requires_grad=False)#whether or not tensor will track the gradients

float_32_tensor.dtype



torch.float32

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

**Getting information from tensors**(**Tensor attributes**)



1. Tensor not right datatype - to do get datatype from a tensor,can use tensor.dtype

2.  Tensor not right shape - to get shape from a tensor,can use tensor.shape

3.  Tensor not on the right device - to get device from a tensor,can use tensor.device
  



In [ ]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6280, 0.6785, 0.0622, 0.6221],
        [0.2649, 0.8504, 0.4308, 0.3112],
        [0.1473, 0.0938, 0.5083, 0.5516]])

In [ ]:
some_tensor.size(),some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
#find out some details about tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.6280, 0.6785, 0.0622, 0.6221],
        [0.2649, 0.8504, 0.4308, 0.3112],
        [0.1473, 0.0938, 0.5083, 0.5516]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu


**Tensor Operations: Manipulating tensors**

**Tensor operations Include:**



*   Addition
*   Subtraction
*   Multiplication(element-wise)
*   Division
*   Matrix Multiplication

In [ ]:
general_tensor = torch.tensor([2,5,10])
general_tensor + 2
#alternative method
#torch.add(general_tensor,2)

tensor([ 4,  7, 12])

In [ ]:
general_tensor * 10
#alternative method using built in function
#torch.mul(general_tensor ,10)

tensor([ 20,  50, 100])

In [ ]:
general_tensor - 10
#alternative method using built in method
torch.sub(general_tensor,10)


tensor([-8, -5,  0])

**Matrix Multiplication**

There are two ways of multiplication in neural networks or deep learning

* Element wise multiplication

* Matrix Multiplication(dot product)

In [ ]:
general_tensor

tensor([ 2,  5, 10])

In [ ]:
#element wise multiplication
print(general_tensor ,"*",general_tensor)
print(general_tensor * general_tensor)

tensor([ 2,  5, 10]) * tensor([ 2,  5, 10])
tensor([  4,  25, 100])


In [ ]:
#matrix multipliaction
torch.matmul(general_tensor,general_tensor)

tensor(129)

In [ ]:
#manual matrix multiplication
#2*2 +5*5 + 10*10
%%time
value=0
for i in range(len(general_tensor)):
  value = value + general_tensor[i] * general_tensor[i]
print(value)

tensor(129)
CPU times: user 119 µs, sys: 958 µs, total: 1.08 ms
Wall time: 910 µs


In [ ]:
%%time
#general_tensor @ general_tensor
torch.matmul(general_tensor , general_tensor)


**note : built in torch methods are fast and efficient**

The most common error in the tensor multiplication is the shape error

* for matrix multiplication:

* the num of columns in first matrix must be equal to the number of rows in the second matrix

* i.e inner dimensions must be equal

* (2,3) @ (2,3) won't work

* (3,2) @ (2,3) will work

* (3,4) @ (4,3) => (3,3)



In [ ]:
import torch
torch.matmul(torch.rand(3,4) , torch.rand(4,3))

tensor([[1.0831, 0.7036, 1.3248],
        [1.2359, 0.7462, 1.8474],
        [1.1551, 0.5211, 1.3983]])

**How to deal with shape errors in matrix multiplication**

* take the transpose of tge any of the matrix
* transpose means changing the axis . i.e changing rows into coulmnn or coulmns into rowns

In [ ]:
tensor_A = torch.tensor([[1,5],[3,9],[8,0]])
tensor_A.shape



torch.Size([3, 2])

In [ ]:
tensor_B = torch.tensor([[3,9],[9,7],[5,8]])
tensor_B.shape

torch.Size([3, 2])

In [ ]:
#as inner dimensions are not equaal , it will throw an error on running

torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
#in order to make the shape compatible , take the transpose of any tensor
Transpose_tensor_A= tensor_A.T  #(2,3)

In [ ]:
torch.matmul(Transpose_tensor_A, tensor_B)


tensor([[ 70,  94],
        [ 96, 108]])

In [ ]:
print(f"tensor_A.shape:{tensor_A.shape} and tensor_B.shape: {tensor_B.shape}")
print("inner dimensions are not equal , thus mulptication is not possible")
print(f"tensor_A.shape :{tensor_A.shape} and tensor_B.transpose.shape: {tensor_B.T.shape}")
print("inner dimensions are equal , thus mulptication is possible")
print(f"The output matrix of outer dimension shape is after matrix multipliaction = {torch.mm(tensor_A,tensor_B.T)}")


tensor_A.shape:torch.Size([3, 2]) and tensor_B.shape: torch.Size([3, 2])
inner dimensions are not equal , thus mulptication is not possible
tensor_A.shape :torch.Size([3, 2]) and tensor_B.transpose.shape: torch.Size([2, 3])
inner dimensions are equal , thus mulptication is possible
The output matrix of outer dimension shape is after matrix multipliaction = tensor([[48, 44, 45],
        [90, 90, 87],
        [24, 72, 40]])


**Tensor Aggregation**

* finding the min , max , mean, sum,etc

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

**Positional min/max**

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


**Change tensor datatype**

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

**Reshaping , stacking , sequeezing and unsequeezing tensors**

The most common problem we encounter while working with tensors is shape incompatibility.

To solve this error , different methods are used , some of which are as follows:


 * **Reshaping:** changing the shape of the tensor with the defined shape.

 * **view :** return a view of the input tensor in a specified shape but both the original tensor and the reshaped tensor via view are pointing to same memory location , changes in one reflects to other as well

* **stacking :** combining the tensors in a dimention specified . By default its vertical dim=0

* **sequeezing:** means removing the single dimension from the input array. i.e removing from double brackets to single brackets

* **unsequeezing:** means adding a new single dimension in the tensor i.e adding a bracket

* **permute:** means modifying the dimensions or axis of the values in the tensors.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

**How about removing all single dimensions from a tensor?**

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**Indexing (selecting data from tensors)**


In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

**PyTorch tensors & NumPy**

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
* torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility (trying to take the random out of random)**

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1292, 0.2910, 0.5557, 0.5907],
        [0.4732, 0.0668, 0.1103, 0.0821],
        [0.4672, 0.0121, 0.3457, 0.7811]])

Tensor B:
tensor([[0.3600, 0.3399, 0.6684, 0.1055],
        [0.5859, 0.0628, 0.0659, 0.8716],
        [0.9857, 0.1330, 0.7371, 0.7844]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

**Running tensors on GPUs (and making faster computations)**

GPUs = faster computations on numbers , credit goes to the CUDA , NVIDIA hardware and Pytorch running behind the scenes to make everything good

Different ways to get or use the gpus :

* Free gpu on google colab

* set the gpu on your own system , this need setup and investments -rent the divices from platforms like AWS , Azure (cloud computing)

In [ ]:
!nvidia-smi

Thu Jul 10 04:55:59 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   62C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

**Getting PyTorch to run on the GPU**

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:

# Count number of devices
torch.cuda.device_count()


1

**Getting PyTorch to run on Apple Silicon**

In [ ]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

False

In [ ]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [ ]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

**Putting tensors (and models) on the GPU**

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

 **Moving tensors back to the CPU**

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)


In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')